#ifndef _BRD4187C_H_
#define _BRD4187C_H_

#define PIN_OUT_SET	    	1
#define PIN_OUT_CLEAR		0

#define MY_USART            USART0
#define MY_USART_CLOCK      cmuClock_USART0
#define MY_USART_TX_SIGNAL  dmadrvPeripheralSignal_USART0_TXBL
#define MY_USART_RX_SIGNAL  dmadrvPeripheralSignal_USART0_RXDATAV

#define SL_WFX_HOST_PINOUT_RESET_PORT SL_GPIO_PORT_A
#define SL_WFX_HOST_PINOUT_RESET_PIN 5
#define SL_WFX_HOST_PINOUT_SPI_WIRQ_PORT SL_GPIO_PORT_A /* SPI IRQ port*/
#define SL_WFX_HOST_PINOUT_SPI_WIRQ_PIN 8          /* SPI IRQ pin */
#define SL_WFX_HOST_PINOUT_WUP_PORT SL_GPIO_PORT_B
#define SL_WFX_HOST_PINOUT_WUP_PIN 5

#define SL_WFX_HOST_PINOUT_SPI_TX_PORT SL_GPIO_PORT_C
#define SL_WFX_HOST_PINOUT_SPI_TX_PIN 1

#define SL_WFX_HOST_PINOUT_SPI_RX_PORT SL_GPIO_PORT_C
#define SL_WFX_HOST_PINOUT_SPI_RX_PIN 2

#define SL_WFX_HOST_PINOUT_SPI_CLK_PORT SL_GPIO_PORT_C
#define SL_WFX_HOST_PINOUT_SPI_CLK_PIN 3

#define SL_WFX_HOST_PINOUT_SPI_CS_PORT SL_GPIO_PORT_C
#define SL_WFX_HOST_PINOUT_SPI_CS_PIN 0

#endif /* _BRD4187C_H_ */